version: '3.8'
services:
  dev:
    container_name: dalia_api_dev
    image: daliabackend
    build:
      context: .
      dockerfile: ./Dockerfile
    command: npm run start:dev
    ports:
      - 4000:4000
    restart: always  
    volumes:
      - .:/app

  redis:
    container_name: redis-resume
    build: 
        context: ./redis
    image: redis        
    ports:
        - 6379:6379 
    volumes:
     - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    # command: redis-server "/usr/local/etc/redis/redis.conf --requirepass $$REDIS_PASSWORD"
    env_file:
      - ./redis/.env
    restart: always 


  mongo:
    container_name: mongo-reusme
    hostname: mongo
    build: 
        context: ./mongo
    ports:
        - 27017:27017
    volumes:
        - db_data_mongo:/data/db
        - ./mongo/mongod.conf:/etc/mongod.conf
        - ./mongo-setup-user.js:/docker-entrypoint-initdb.d/mongo-setup-user.js:ro
    restart: always
    command: --config /etc/mongod.conf  

volumes:
  db_data_mongo:     
